apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hyy993xwn-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hyy993xwn-go 
  name: hyy993xwn-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hyy993xwn-go 
